default: styles/application.scss
tangerineui-cherry: styles/tangerineui-cherry.scss
tangerineui-lagoon: styles/tangerineui-lagoon.scss
tangerineui-orange: styles/tangerineui-orange.scss
tangerineui-grape: styles/tangerineui-grape.scss
modern: styles/modern.scss
bird: styles/bird.scss
